apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: guestbook
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Zeeshan50522/argocd-k8s.git
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    syncOptions:
    - CreateNamesapce=true

    automated:
      selfHeal: true
      prune: true